### ISSUE TITLE
syntax error with  raise type(self._exception), self._exception, self._traceback (_base.py)

### ISSUE THREAD

**Issue by sdpython** [agronholm/pythonfutures#41] opened 2015-07-14 20:06 UTC
I installed futures 3.0.3 and it raised the following exception:

    from IPython.kernel import KernelManager
  File "c:\apythonensae\python\lib\site-packages\IPython\kernel\__init__.py", line 4, in <module>
    from . import zmq
  File "c:\apythonensae\python\lib\site-packages\IPython\kernel\zmq\__init__.py", line 10, in <module>
    from .session import Session
  File "c:\apythonensae\python\lib\site-packages\IPython\kernel\zmq\session.py", line 41, in <module>
    from zmq.eventloop.ioloop import IOLoop
  File "c:\apythonensae\python\lib\site-packages\zmq\eventloop\__init__.py", line 3, in <module>
    from zmq.eventloop.ioloop import IOLoop
  File "c:\apythonensae\python\lib\site-packages\zmq\eventloop\ioloop.py", line 35, in <module>
    from tornado.ioloop import PollIOLoop, PeriodicCallback
  File "c:\apythonensae\python\lib\site-packages\tornado\ioloop.py", line 46, in <module>
    from tornado.concurrent import TracebackFuture, is_future
  File "c:\apythonensae\python\lib\site-packages\tornado\concurrent.py", line 37, in <module>
    from concurrent import futures
  File "c:\apythonensae\python\lib\site-packages\concurrent\futures\__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "c:\apythonensae\python\lib\site-packages\concurrent\futures\_base.py", line 355
    raise type(self._exception), self._exception, self._traceback
                               ^
SyntaxError: invalid syntax

**Comment by agronholm** [comment] 2015-07-14 20:49
Not sure what to say. How can I reproduce it?

**Comment by agronholm** [comment] 2015-07-15 16:52
Do you get this without ipython?

**Comment by sdpython** [comment] 2015-07-15 17:00
Hi,

Sorry for the delay, I got this error while running a notebook offline.
I'll try to send you a short example to replicate.

Xavier

**Comment by sdpython** [comment] 2015-07-18 08:57
This issue happens when I run python from a virtual environment on Windows (standard distribution) and I type the following instruction :

from IPython.kernel import KernelManager

Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:44:40) [MSC v.1600 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from IPython.kernel import KernelManager
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\python34_x64\lib\site-packages\IPython\kernel\__init__.py", line 4, in <module>
    from . import zmq
  File "c:\python34_x64\lib\site-packages\IPython\kernel\zmq\__init__.py", line 10, in <module>
    from .session import Session
  File "c:\python34_x64\lib\site-packages\IPython\kernel\zmq\session.py", line 41, in <module>
    from zmq.eventloop.ioloop import IOLoop
  File "c:\python34_x64\lib\site-packages\zmq\eventloop\__init__.py", line 3, in <module>
    from zmq.eventloop.ioloop import IOLoop
  File "c:\python34_x64\lib\site-packages\zmq\eventloop\ioloop.py", line 35, in <module>
    from tornado.ioloop import PollIOLoop, PeriodicCallback
  File "c:\python34_x64\lib\site-packages\tornado\ioloop.py", line 46, in <module>
    from tornado.concurrent import TracebackFuture, is_future
  File "c:\python34_x64\lib\site-packages\tornado\concurrent.py", line 37, in <module>
    from concurrent import futures
  File "c:\python34_x64\lib\site-packages\concurrent\futures\__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "c:\python34_x64\lib\site-packages\concurrent\futures\_base.py", line 355
    raise type(self._exception), self._exception, self._traceback
                               ^

The issue does not happen when I don't use virtual environment.

**Comment by agronholm** [comment] 2015-07-20 14:59
There is nothing wrong with the syntax on the highlighted line, so I'm guessing this is about IPython. If you import the module in question without ipython, you don't get the same error, right?

**Comment by agronholm** [comment] 2015-07-30 11:13
And for the record, your traceback refers to Python 3.4, which has nothing whatsoever to do with my backport.

**Comment by agronholm** [comment] 2015-07-30 11:19
Looking at it more carefully, it seems like you've installed my backport to Python 3.4, which already has that package in its standard library. Care to explain?

**Comment by sdpython** [comment] 2015-07-30 11:22
Hi,

I need to check but I think some packages still refers to it in their
dependencies (which means I need to start from scratch and install packages
one by one to see which one is doing it). I don't explicitely install it.

Xavier

**Comment by agronholm** [comment] 2015-07-30 11:25
Ok. The backport uses 2.x syntax so it is not intended to work on Python 3 at all.
The author of some library probably didn't make the dependency conditional on the Python version.

**Comment by PHLAK** [comment] 2015-08-01 22:04
I'm seeing this same error when installing futures with pip:

    Running setup.py install for futures
        File "/usr/local/lib/python3.4/dist-packages/concurrent/futures/_base.py", line 355
          raise type(self._exception), self._exception, self._traceback
                                     ^
      SyntaxError: invalid syntax

**Comment by agronholm** [comment] 2015-08-02 09:02
Why would you install futures on Python 3.4?

**Comment by agronholm** [comment] 2015-08-03 14:25
Since there has been no further feedback and it appears that everyone involved mistakenly tried to use this on Python 3, I'm closing the issue.

**Closed by agronholm** 2015-08-03 14:25 UTC

**Comment by sinwar** [comment] 2017-02-17 05:49
Even I also did the same mistake and used it with python 3.x which raised the same issue.

**Comment by jmehnle** [comment] 2018-02-02 20:44
The [README](https://github.com/agronholm/pythonfutures/blob/master/README.rst) now makes it a point to not install this on 3.x.

**Comment by agronholm** [comment] 2018-02-03 10:09
Installing it normally should not even be a problem, as Python prefers standard library imports over everything else by default.

**Comment by RafiC92** [comment] 2018-11-20 08:04
I still get this issue on python 3, even when I try to pip install something:

Traceback (most recent call last):
  File "/usr/local/bin/pip", line 7, in <module>
    from pip._internal import main
  File "/volumes/dependencies/lib/python3.6/site-packages/pip/_internal/__init__.py", line 40, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/volumes/dependencies/lib/python3.6/site-packages/pip/_internal/cli/autocompletion.py", line 8, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/volumes/dependencies/lib/python3.6/site-packages/pip/_internal/cli/main_parser.py", line 12, in <module>
    from pip._internal.commands import (
  File "/volumes/dependencies/lib/python3.6/site-packages/pip/_internal/commands/__init__.py", line 6, in <module>
    from pip._internal.commands.completion import CompletionCommand
  File "/volumes/dependencies/lib/python3.6/site-packages/pip/_internal/commands/completion.py", line 6, in <module>
    from pip._internal.cli.base_command import Command
  File "/volumes/dependencies/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 23, in <module>
    from pip._internal.index import PackageFinder
  File "/volumes/dependencies/lib/python3.6/site-packages/pip/_internal/index.py", line 31, in <module>
    from pip._internal.models.link import Link
  File "/volumes/dependencies/lib/python3.6/site-packages/pip/_internal/models/link.py", line 9, in <module>
    from pip._internal.wheel import wheel_ext
  File "/volumes/dependencies/lib/python3.6/site-packages/pip/_internal/wheel.py", line 7, in <module>
    import compileall
  File "/usr/local/lib/python3.6/compileall.py", line 20, in <module>
    from concurrent.futures import ProcessPoolExecutor
  File "/volumes/dependencies/lib/python3.6/site-packages/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "/volumes/dependencies/lib/python3.6/site-packages/concurrent/futures/_base.py", line 381
    raise exception_type, self._exception, self._traceback
                        ^
SyntaxError: invalid syntax


Any help on how to remove this?

**Comment by agronholm** [comment] 2018-11-20 08:17
Yes – don't install it on Python 3. There are a number of countermeasures in place to prevent this from happening and you're working around all of them.

**Comment by RafiC92** [comment] 2018-11-20 08:22
I dont install it myself, its probably a dependency for one of my packages. any ideas how to avoid installing it?

**Comment by agronholm** [comment] 2018-11-20 08:50
Installing `futures` does not by itself cause any harm on Python 3 because `PYTHONPATH` favors standard library packages over 3rd party ones. The problem starts when one has overridden `PYTHONPATH` to prefer outside packages over the standard library. This is what is happening on your system.

If `futures` is a dependency of one of your dependencies, you can find out which one(s) when using pip to install your package.

**Comment by agronholm** [comment] 2018-11-20 09:46
Can you post your install log? As you can see here, flask has no direct dependency on futures:
https://github.com/pallets/flask/blob/master/setup.py#L36-L41

**Comment by RafiC92** [comment] 2018-11-20 11:04
OK, I managed to make this work by deleting the concurent directory in that directory and copying the native python cocurrent directory instead. But I still dont know how I would do this dynamically inside the container every time I run it. I would like to avoid messy bash scripts. 
If you have any ideas, please share. Thanks :)

**Comment by agronholm** [comment] 2018-11-20 12:03
The culprit seems to be here: https://bitbucket.org/zhuoqiang/goslate/src/a753c6ffc9e2f606e2c9ea0d62e956b6826e2a7e/setup.py?at=default&fileviewer=file-view-default#setup.py-31 (unconditional requirement).
