### ISSUE TITLE
error: can't start new thread

### ISSUE THREAD

**Issue by lansman** [agronholm/pythonfutures#36] opened 2015-04-14 04:18 UTC
Windows 7 x64, python 2.7.9
I use requests-features library which uses python-futures.

I call this usual code (got from requests-futures examples) that makes requests to some internet-API many-many times in loop. And it seems it creates 1 new thread per each request, so it seems bug. 

from requests_futures.sessions import FuturesSession as SessionAsync
session = SessionAsync(max_workers=2)
resp = session.get(self.main_address,
                   params=self.query_params,
                   background_callback=self.parse_response,
                   proxies=...,
                   timeout=...)

When loops counter comes to ~600 and number of threads comes to 600, fall occurs:

  File "C:\myscript.py", line 223, in get_coords_for_addr
    timeout=self.web_config.timeout)
  File "C:\Python27\ArcGIS10.2\lib\site-packages\requests\sessions.py", line 476, in get
    return self.request('GET', url, **kwargs)
  File "C:\Python27\ArcGIS10.2\lib\site-packages\requests_futures\sessions.py", line 73, in request
    return self.executor.submit(func, *args, **kwargs)
  File "C:\Python27\ArcGIS10.2\lib\site-packages\concurrent\futures\thread.py", line 111, in submit
    self._adjust_thread_count()
  File "C:\Python27\ArcGIS10.2\lib\site-packages\concurrent\futures\thread.py", line 127, in _adjust_thread_count
    t.start()
  File "C:\Python27\ArcGIS10.2\lib\threading.py", line 745, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread

**Comment by agronholm** [comment] 2015-05-02 20:31
Could you provide an example which reproduces the problem that uses ThreadPoolExecutor directly?

**Comment by agronholm** [comment] 2016-02-26 05:16
Closing as this looks like a system limitation (you're not supposed to create that many threads!).

**Closed by agronholm** 2016-02-26 05:16 UTC
Labels: awaiting input
